### ISSUE TITLE
Deprecation errors on PHP8.1

### ISSUE THREAD

**Issue by phinor** [D4H/php-finediff#5]
Receiving the following error on systems with PHP 8.1:

```PHP Deprecated · Return type of FineDiff\Granularity\Word::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice```

I note the pull request #4 has addressed this issue, but still needs to be approved.

**Comment by mrdan** [comment]
Thanks for the heads up, this has been merged
